# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
# Exercise 1
import numpy as np

arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [3]:
# Exercise 2
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [4]:
# Exercise 3
import numpy as np

evenly_spaced = np.linspace(0, 5, 10)
print(evenly_spaced)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [5]:
# Exercise 4
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [6]:
# Exercise 5
import numpy as np

random_matrix = np.random.rand(4, 4)
print(random_matrix)


[[0.67828444 0.84556267 0.98655409 0.53593025]
 [0.74241852 0.72621534 0.02931426 0.28153531]
 [0.26393709 0.79098768 0.24814418 0.07941852]
 [0.82284306 0.16775979 0.68815158 0.85081648]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [7]:
# Exercise 6
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)


(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [8]:
# Exercise 7
import numpy as np

arr = np.arange(16)  # Creates a 1D array with values from 0 to 15
reshaped_matrix = arr.reshape(4, 4)
print(reshaped_matrix)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [11]:
# Exercise 8
import numpy as np

arr = np.array([0.1, 0.2, 3])
print(arr.dtype)


float64



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [10]:
# Exercise 9
import numpy as np

# Create an array from 1 to 100
arr = np.arange(1, 101)

# Find even numbers using a boolean mask
even_numbers = arr[arr % 2 == 0]

print(even_numbers)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [12]:
# Exercise 10
import numpy as np

random_int_matri = np.random.randint(10, 51, size=(6, 6))
print(random_int_matri)


[[47 15 17 25 49 30]
 [20 40 13 13 26 47]
 [31 43 13 30 34 21]
 [26 23 39 14 23 16]
 [22 44 18 31 21 42]
 [27 26 11 22 15 48]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [13]:
# Exercise 11
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
submatrix = matrix[0:2, 1:3]
print(submatrix)


[[2 3]
 [5 6]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [14]:
# Exercise 12
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = arr.sum()

print(total_sum)


21



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [15]:
# Exercise 13
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [16]:
# Exercise 14
import numpy as np

arr = np.array([3, 7, 1, 9, 4])

max_value = arr.max()
min_value = arr.min()

print("Maximum:", max_value)
print("Minimum:", min_value)


Maximum: 9
Minimum: 1



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [17]:
# Exercise 15
import numpy as np
arr = np.random.randint(1, 101, size=20)
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of maximum value:", max_index)
print("Maximum value:", arr[max_index])


Array: [ 57  57  73  45  63  40  98  90  55  70  28  98  69  83  17   2  78  76
  94 100]
Index of maximum value: 19
Maximum value: 100



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [18]:
# Exercise 16
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [10 20 30 40 50]
Reversed array: [50 40 30 20 10]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [19]:
# Exercise 17
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
result = A * B 

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Element-wise multiplication:\n", result)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [20]:
# Exercise 18
import numpy as np

arr = np.array([1, 2, 3, 4])
diag_matrix = np.diag(arr)

print("1D array:", arr)
print("Diagonal matrix:\n", diag_matrix)


1D array: [1 2 3 4]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [21]:
# Exercise 19
import numpy as np
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
result = A @ B  

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix multiplication result:\n", result)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix multiplication result:
 [[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [22]:
# Exercise 20
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_flat = arr_2d.flatten()  

print("Original 2D array:\n", arr_2d)
print("Flattened 1D array:", arr_flat)


Original 2D array:
 [[1 2 3]
 [4 5 6]]
Flattened 1D array: [1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [23]:
# Exercise 21
import numpy as np
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
stacked = np.vstack((a, b))

print("Array A:\n", a)
print("Array B:\n", b)
print("Vertically stacked array:\n", stacked)


Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [24]:
# Exercise 22
import numpy as np
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
stacked = np.hstack((a, b))

print("Array A:\n", a)
print("Array B:\n", b)
print("Horizontally stacked array:\n", stacked)


Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Horizontally stacked array:
 [[1 2 5 6]
 [3 4 7 8]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [25]:
# Exercise 23
import numpy as np

arr = np.arange(9) 

sub_arrays = np.split(arr, 3)
print(sub_arrays)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [26]:
# Exercise 24
import numpy as n
arr = np.random.rand(3, 3)
rounded_arr = np.round(arr, 2)

print("Original array:\n", arr)
print("Rounded array:\n", rounded_arr)


Original array:
 [[0.18148025 0.84298284 0.69426558]
 [0.95528415 0.04165011 0.55617138]
 [0.07623511 0.61163783 0.68086056]]
Rounded array:
 [[0.18 0.84 0.69]
 [0.96 0.04 0.56]
 [0.08 0.61 0.68]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [27]:
# Exercise 25
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5])

unique_elements = np.unique(arr)

print("Original array:", arr)
print("Unique elements:", unique_elements)


Original array: [1 2 2 3 4 4 5]
Unique elements: [1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [28]:
# Exercise 26
import numpy as np

arr = np.array([2, 4, 6, 1, 8, 3])
arr[arr < 5] = 5
print(arr)


[5 5 6 5 8 5]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [29]:
# Exercise 27
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(arr)

print("Original array:", arr)
print("Cumulative sum:", cumulative_sum)


Original array: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [30]:
# Exercise 28
import numpy as np

arr = np.array([0, 1, 2, 0, 3, 0, 4])

non_zero_count = np.count_nonzero(arr)
print("Array:", arr)
print("Number of non-zero elements:", non_zero_count)


Array: [0 1 2 0 3 0 4]
Number of non-zero elements: 4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [31]:
# Exercise 29
import numpy as np
arr = np.random.randint(1, 101, size=10)
sorted_arr = np.sort(arr)

print("Original array:", arr)
print("Sorted array:", sorted_arr)


Original array: [66 39 79 80 42 87 33 67 58 61]
Sorted array: [33 39 42 58 61 66 67 79 80 87]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [32]:
# Exercise 30
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_sums = matrix.sum(axis=1)
col_sums = matrix.sum(axis=0)

print("Matrix:\n", matrix)
print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row-wise sums: [ 6 15 24]
Column-wise sums: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [33]:
# Exercise 31
import numpy as np

arr = np.random.rand(4, 4) * 100  
arr_min = arr.min()
arr_max = arr.max()
normalized_arr = (arr - arr_min) / (arr_max - arr_min)

print("Original array:\n", arr)
print("\nNormalized array:\n", normalized_arr)


Original array:
 [[78.57341807 31.11422029  9.93246555 25.48945996]
 [18.00901205 32.50139508 41.23586765  4.45451967]
 [27.05196813 34.50701681 36.92690111 72.79771016]
 [24.08026803 43.9339597  92.38432365 57.87360763]]

Normalized array:
 [[0.8429326  0.303193   0.06229908 0.23922424]
 [0.15415129 0.31896893 0.41830354 0.        ]
 [0.25699419 0.34177828 0.36929892 0.77724716]
 [0.22319791 0.44898815 1.         0.6075197 ]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [34]:
# Exercise 32
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)  # or a @ b

print("Array a:", a)
print("Array b:", b)
print("Dot product:", dot_product)


Array a: [1 2 3]
Array b: [4 5 6]
Dot product: 32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [35]:
# Exercise 33
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace_value = np.trace(matrix)

print("Matrix:\n", matrix)
print("Trace:", trace_value)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [36]:
# Exercise 34
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:\n", arr)

# Swap row 0 and row 2
arr[[0, 2]] = arr[[2, 0]]

print("\nArray after swapping rows 0 and 2:\n", arr)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping rows 0 and 2:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [37]:
# Exercise 35
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Convert to column vector (shape: (5, 1))
column_vector = arr.reshape(-1, 1)

print("Original 1D array:", arr)
print("Column vector:\n", column_vector)


Original 1D array: [1 2 3 4 5]
Column vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [41]:
# Exercise 36
import numpy as np

matrix = np.array([[1, 2, 3],
                   [2, 7, 3],
                   [3, 2, 1]])

determinant = np.linalg.det(matrix)

print("Matrix:\n", matrix)
print("Determinant:", determinant)


Matrix:
 [[1 2 3]
 [2 7 3]
 [3 2 1]]
Determinant: -36.0



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [43]:
# Exercise 37
import numpy as np

matrix = np.array([[3, 2],
                   [1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:\n", matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix:
 [[3 2]
 [1 2]]
Eigenvalues: [4. 1.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [46]:
# Exercise 38
import numpy as np
A = np.array([[2, 3],
              [2, 4]])
b = np.array([2, 3])
x = np.linalg.solve(A, b)

print("Solution:", x)


Solution: [-0.5  1. ]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [49]:
# Exercise 39
import numpy as np
arr = np.array([6, 2, 3, 4, 5], dtype=float)
noise = np.random.normal(loc=0, scale=5, size=arr.shape)
noisy_arr = arr + noise

print("Original array:", arr)
print("Noise:", noise)
print("Array with Gaussian noise:", noisy_arr)


Original array: [6. 2. 3. 4. 5.]
Noise: [  6.25526509   3.46835508  10.75809715 -11.86234683   3.97338474]
Array with Gaussian noise: [12.25526509  5.46835508 13.75809715 -7.86234683  8.97338474]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [50]:
# Exercise 40
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
diagonal_elements = np.diagonal(matrix)

print("Matrix:\n", matrix)
print("Diagonal elements:", diagonal_elements)


Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [55]:
# Exercise 41
import numpy as np
arr = np.random.rand(100) * 100
clipped_arr = np.clip(arr, 10, 50)

print("Original array:\n", arr)
print("\nClipped array:\n", clipped_arr)


Original array:
 [28.90886821 16.15484871 43.62422992 18.04640614 55.77354861 58.95469528
 77.57759929 25.54125785 26.56069099 41.61881417 81.60786963 84.54304918
 20.06593917 67.7904433  68.8930564  55.22061911 49.57617209 10.84075824
 38.55004186 59.15192437 78.2876058  34.72778867 81.02944573 60.20343845
 18.68438839 58.01090837 27.31973729 84.74768949 91.35627677 26.88753183
 42.22348818 16.21592167 82.88697165 74.20906591 42.66911951 90.2601286
 73.218105   80.46494662 29.76418792 34.69739164 74.733913   35.96694583
 78.03293852  4.5672134  76.75102827 10.73259444 12.98158343  0.40693774
  1.0271734  21.70552691 16.52832206 36.51190878 78.6935947  84.91676145
 16.07870439 44.43852706 69.62536432 72.67378278 20.61674588  9.82279092
 80.38776992 17.35260725 72.76895945  0.67698833 62.7145142  80.22158177
 96.36830664 71.48135769 34.67723971 82.98507991 46.38009432 68.82943981
 98.96259301 44.20879986 36.70155572 54.48473304 55.43741174 72.17490628
  9.76016035 55.76940818 56.7385233


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [56]:
# Exercise 42
import numpy as np
arr = np.array([[ 1, -2,  3],
                [-4,  5, -6],
                [ 7, -8,  9]])

print("Original array:\n", arr)
arr[arr < 0] = 0

print("\nArray after replacing negatives with zero:\n", arr)


Original array:
 [[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]

Array after replacing negatives with zero:
 [[1 0 3]
 [0 5 0]
 [7 0 9]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [57]:
# Exercise 43
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product = np.inner(a, b)
outer_product = np.outer(a, b)

print("Inner product:", inner_product)
print("\nOuter product:\n", outer_product)


Inner product: 32

Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [59]:
# Exercise 44
import numpy as np
from scipy.spatial.distance import cdist
points = np.array([[1, 2],
                   [4, 6],
                   [7, 8],
                   [2, 3]])
distances = cdist(points, points, metric='euclidean')

print("Pairwise distances:\n", distances)


Pairwise distances:
 [[0.         5.         8.48528137 1.41421356]
 [5.         0.         3.60555128 3.60555128]
 [8.48528137 3.60555128 0.         7.07106781]
 [1.41421356 3.60555128 7.07106781 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [60]:
# Exercise 45
import numpy as np
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]
data = np.array([('Alice', 25, 5.5),
                 ('Bob', 30, 6.0),
                 ('Charlie', 22, 5.8)], dtype=dtype)

print(data)
print("\nNames:", data['name'])
print("Ages:", data['age'])
print("Heights:", data['height'])


[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 22, 5.8)]

Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 22]
Heights: [5.5 6.  5.8]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [61]:
# Exercise 46
import numpy as np
matrix = np.random.randint(0, 10, size=(5, 5))

print("Matrix:\n", matrix)
unique_values, counts = np.unique(matrix, return_counts=True)

print("\nUnique values:", unique_values)
print("Counts:", counts)


Matrix:
 [[2 6 0 5 6]
 [5 7 1 8 0]
 [0 0 4 3 0]
 [0 1 3 9 1]
 [6 3 4 3 9]]

Unique values: [0 1 2 3 4 5 6 7 8 9]
Counts: [6 3 1 4 2 2 3 1 1 2]



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [62]:
# Exercise 47
import numpy as np
arr = np.random.rand(3, 3)

print("Original array:\n", arr)
row_means = arr.mean(axis=1, keepdims=True)
centered_arr = arr - row_means

print("\nRow means:\n", row_means)
print("\nCentered array:\n", centered_arr)


Original array:
 [[0.03539488 0.9520414  0.87891669]
 [0.82200308 0.78381381 0.59978876]
 [0.33190312 0.90422748 0.74272235]]

Row means:
 [[0.62211766]
 [0.73520189]
 [0.65961765]]

Centered array:
 [[-0.58672278  0.32992374  0.25679904]
 [ 0.0868012   0.04861193 -0.13541312]
 [-0.32771453  0.24460983  0.0831047 ]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [63]:
# Exercise 48
import numpy as np
arr = np.random.randint(0, 100, size=10)

print("Array:", arr)
has_greater_than_50 = np.any(arr > 50)

print("Any value greater than 50?", has_greater_than_50)


Array: [30 49 37 43 46 20 78 23 26  4]
Any value greater than 50? True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [64]:
# Exercise 49
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
window_size = 3
moving_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

print("Original array:", arr)
print("Moving average:", moving_avg)


Original array: [10 20 30 40 50 60]
Moving average: [20. 30. 40. 50.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [65]:
# Exercise 50
import numpy as np
x = np.array([10, 20, 30, 40, 50])
y = np.array([12, 22, 29, 41, 52])
corr_matrix = np.corrcoef(x, y)
pearson_corr = corr_matrix[0, 1]

print("Correlation matrix:\n", corr_matrix)
print("\nPearson correlation coefficient:", pearson_corr)


Correlation matrix:
 [[1.         0.99659941]
 [0.99659941 1.        ]]

Pearson correlation coefficient: 0.9965994064698636



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [66]:
# Exercise 51
import numpy as np
radians = np.array([0, np.pi/6, np.pi/4, np.pi/2, np.pi])
degrees = np.degrees(radians)
print("Radians:", radians)
print("Degrees:", degrees)


Radians: [0.         0.52359878 0.78539816 1.57079633 3.14159265]
Degrees: [  0.  30.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [67]:
# Exercise 52
import numpy as np
arr = np.random.rand(10) * 100
variance = np.var(arr)

std_dev = np.std(arr)

print("Array:", arr)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Array: [42.98839101 40.11486652 13.73978995 49.76044108 57.51376557  7.61556657
 61.94628855 58.49659637 63.72887854 79.84762871]
Variance: 455.01091038679095
Standard Deviation: 21.330984749579446



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [68]:
# Exercise 53
import numpy as np
arr = np.array([[10, 50, 30],
                [60, 20, 90],
                [40, 70, 80]])

print("Array:\n", arr)
max_indices_axis0 = np.argmax(arr, axis=0)
max_indices_axis1 = np.argmax(arr, axis=1)

print("\nMax indices along axis 0 (columns):", max_indices_axis0)
print("Max indices along axis 1 (rows):", max_indices_axis1)


Array:
 [[10 50 30]
 [60 20 90]
 [40 70 80]]

Max indices along axis 0 (columns): [1 2 1]
Max indices along axis 1 (rows): [1 2 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [69]:
# Exercise 54
import numpy as np
matrix = np.array([[4, 7],
                   [2, 6]])
inverse_matrix = np.linalg.inv(matrix)

print("Original matrix:\n", matrix)
print("\nInverse matrix:\n", inverse_matrix)


Original matrix:
 [[4 7]
 [2 6]]

Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [70]:
# Exercise 55
import numpy as np
arr = np.random.rand(10) * 100  
mean = np.mean(arr)
std = np.std(arr)
standardized = (arr - mean) / std

print("Original array:", arr)
print("Standardized array:", standardized)
print("Mean of standardized:", np.mean(standardized))
print("Variance of standardized:", np.var(standardized))


Original array: [60.72259949 84.09223685 45.10299961 53.67599116 18.30798279 87.37162318
 78.83664056 76.90970289 25.41943672 51.27210052]
Standardized array: [ 0.11178611  1.13566754 -0.57254707 -0.19694318 -1.74650282  1.27934553
  0.9054069   0.82098302 -1.43493249 -0.30226355]
Mean of standardized: 3.9412917374193055e-16
Variance of standardized: 1.0



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [ ]:
# Exercise 56
import numpy as np
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
addition = a + b
subtraction = a - b
print("Array a:", a)
print("Array b:", b)
print("\nAddition:", addition)
print("Subtraction:", subtraction)



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [72]:
# Exercise 57
import numpy as np
arr = np.random.rand(5) 
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of max element:", max_index)
print("Max value:", arr[max_index])


Array: [0.1804107  0.98027741 0.3857143  0.99879335 0.71388732]
Index of max element: 3
Max value: 0.9987933547269677



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [73]:
# Exercise 58
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rotated_arr = np.rot90(arr)

print("Original array:\n", arr)
print("\nRotated by 90 degrees:\n", rotated_arr)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Rotated by 90 degrees:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [74]:
# Exercise 59
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

fro_norm = np.linalg.norm(matrix, ord='fro')

print("Matrix:\n", matrix)
print("\nFrobenius norm:", fro_norm)


Matrix:
 [[1 2 3]
 [4 5 6]]

Frobenius norm: 9.539392014169456



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [75]:
# Exercise 60
import numpy as np
arr = np.arange(3*4*5).reshape(3, 4, 5)

print("Original array shape:", arr.shape)
print(arr)
subarray = arr[0:2, 1:3, 2:5]

print("\nSliced subarray shape:", subarray.shape)
print(subarray)


Original array shape: (3, 4, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

Sliced subarray shape: (2, 2, 3)
[[[ 7  8  9]
  [12 13 14]]

 [[27 28 29]
  [32 33 34]]]



---